### ISSUE TITLE
Make the charter’s principles machine readable

### ISSUE THREAD

**Issue by pietercolpaert** [smartflanders/smartflanders.github.io#11]
Make an `id=...` for every principle and link them to the page of the charter through RDFa.

Proposed by @bartrosseau

Proposal:

```turtle
<https://smart.flanders.be/open-data-charter> a foaf:Document ;
                  dct:license <http://data.vlaanderen.be/id/licentie/creative-commons-zero-verklaring/v1.0>,
                                    <https://creativecommons.org/publicdomain/zero/1.0/>;
                  foaf:topic <https://smart.flanders.be/open-data-charter#1>,<https://smart.flanders.be/open-data-charter#2>, <https://smart.flanders.be/open-data-charter#3>,
                             <https://smart.flanders.be/open-data-charter#4>, <https://smart.flanders.be/open-data-charter#5>, <https://smart.flanders.be/open-data-charter#6>, 
                             <https://smart.flanders.be/open-data-charter#7>, <https://smart.flanders.be/open-data-charter#8>, <https://smart.flanders.be/open-data-charter#9>,
                             <https://smart.flanders.be/open-data-charter#10>, <https://smart.flanders.be/open-data-charter#11>,<https://smart.flanders.be/open-data-charter#12>, 
                             <https://smart.flanders.be/open-data-charter#13>, <https://smart.flanders.be/open-data-charter#14>, <https://smart.flanders.be/open-data-charter#15>,
                             <https://smart.flanders.be/open-data-charter#16>, <https://smart.flanders.be/open-data-charter#17>, <https://smart.flanders.be/open-data-charter#18>,
                             <https://smart.flanders.be/open-data-charter#19>, <https://smart.flanders.be/open-data-charter#20>.

<https://smart.flanders.be/open-data-charter#1> rdfs:label "Open by default"@nl, "Open by default"@en;
                       rdfs:comment "Data die door, in of over de stad gecapteerd worden, worden standaard als open data ter beschikking gesteld voor hergebruik."@nl, "..."@en.
#...
```

**Comment by bartrosseau** [comment]
Merci ☺

Met vriendelijke groeten
Bart Rosseau

Diensthoofd

Data en Informatie - Bedrijfsvoering - Stad Gent

è Bezoekadres: Franklin Rooseveltlaan 1

[http://emailbanner.gent.be/sites/all/themes/bootstrap/img/postadres.png]

Postadres: stadhuis, Botermarkt 1, 9000 Gent

Tel. 09 266 56 25
GSM 0478 20 56 11

Word een echte Gentkenner: http://hoeveelin.stad.gent
Meer cijfers over Gent? Ontdek hier<https://stad.gent/over-gent-en-het-stadsbestuur/over-gent/kaarten-cijfers-en-data/gent-gescand> het aanbod

Internet stad.gent<http://stad.gent/>






Aansprakelijkheidsbeperker
Deze e-mail en bijlagen kunnen informatie bevatten die vertrouwelijk is en/of beschermd wordt door intellectuele eigendomsrechten. Lees meer ... <https://stad.gent/over-gent-en-het-stadsbestuur/vragen-suggesties-en-meldingen/aansprakelijkheidsbeperker>

Van: Pieter Colpaert [mailto:notifications@github.com]
Verzonden: vrijdag 19 oktober 2018 10:33
Aan: smartflanders/smartflanders.github.io
CC: Rosseau Bart; Mention
Onderwerp: [smartflanders/smartflanders.github.io] Make the charter’s principles machine readable (#11)


Make an id=... for every principle and link them to the page of the charter through RDFa.

Proposed by @bartrosseau<https://github.com/bartrosseau>

Proposal:

<https://smart.flanders.be/open-data-charter> a foaf:Document ;

                  foaf:topic <https://smart.flanders.be/open-data-charter#1>,<https://smart.flanders.be/open-data-charter#2>, <https://smart.flanders.be/open-data-charter#3>, <https://smart.flanders.be/open-data-charter#4>, <https://smart.flanders.be/open-data-charter#5>, <https://smart.flanders.be/open-data-charter#6>, <https://smart.flanders.be/open-data-charter#7>, <https://smart.flanders.be/open-data-charter#8>, <https://smart.flanders.be/open-data-charter#9>,<https://smart.flanders.be/open-data-charter#10>, <https://smart.flanders.be/open-data-charter#11>,<https://smart.flanders.be/open-data-charter#12>, <https://smart.flanders.be/open-data-charter#13>, <https://smart.flanders.be/open-data-charter#14>, <https://smart.flanders.be/open-data-charter#15>, <https://smart.flanders.be/open-data-charter#16>, <https://smart.flanders.be/open-data-charter#17>, <https://smart.flanders.be/open-data-charter#18>, <https://smart.flanders.be/open-data-charter#19>, <https://smart.flanders.be/open-data-charter#20>.

<https://smart.flanders.be/open-data-charter#1> rdfs:title "Open by default"@nl, "Open by default"@en;

                       rdfs:comment "Data die door, in of over de stad gecapteerd worden, worden standaard als open data ter beschikking gesteld voor hergebruik."@nl, "..."@en.

#...
