### ISSUE TITLE
Tekst 'VLOCA' aanpassen

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#16]
inhoudelijke tekst op pagina 'VLOCA' moet gewijzigd worden met tekst in doc. Ook afbeelding in doc moet plaats krijgen op pagina + call to action naar VLOCA Portaal met Groen kadertje (zoals op homepage met 'over')

[VLOCA.docx](https://github.com/smartflanders/smartflanders.github.io/files/5155317/VLOCA.docx)

**Comment by plenaerts** [comment]
@kdaems er zit geen afbeelding in doc

**Comment by KDaems** [comment]
https://vlaamseoverheid.sharepoint.com/:i:/r/sites/ABB-VLOCA/Website/Afbeeldingen/ABB_Highres.png?csf=1&web=1&e=T94KuP

https://vlaamseoverheid.sharepoint.com/:i:/r/sites/ABB-VLOCA/Website/Afbeeldingen/ABB_Highres.jpg?csf=1&web=1&e=U9gDgz

zowel jpg als png.

**Comment by KDaems** [comment]
Tekst is niet over gelijk inspringend + titel moet 'Vlaamse Open City Architectuur' zijn ipv 'over vloca'
