### ISSUE TITLE
Tekst 'Open Data Charter' aanpassen

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#18]
inhoudelijke tekst op pagina 'Open Data Charter' moet gewijzigd worden met tekst in doc.
[Open Data Charter.docx](https://github.com/smartflanders/smartflanders.github.io/files/5155332/Open.Data.Charter.docx)

**Comment by plenaerts** [comment]
Hierin zit allerlei opmaak die niet evident zal zijn...

**Comment by KDaems** [comment]
Het Charter zelf is ook nog machine leesbaar gemaakt indertijd.
