### ISSUE TITLE
Homepage aanpassen

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#21]
Homepage aanpassen:
- 'Meer weten over VLOCA' aanpassen naar 'Meer weten over Open Data Charter' met link naar juiste page
- 'Meer weten over Smart Flanders' -> linken naar juiste page 'Over'
- Afbeelding Smarrt Flanders 2.0 wijzigen met afbeelding
![Vlaanderen Sterke Steden (3)](https://user-images.githubusercontent.com/66940179/91835966-6c7ba900-ec4a-11ea-881d-187fa7a5c282.jpg)
- 'Alles over de financiering' -> zonder 'de'
- Direct naar: externe link naar 'stedenbeleid.vlaanderen.be' en vloca.vlaanderen.be; interne link naar 'datapiloten'
- 'Goede praktijken' -> verbergen
- link groen kader Open Data Charter naar juiste page verwijzen.
- enkele interessante links -> verbergen
- Contact: e-mail -> stedenbeleid@vlaanderen.be aanpassen
- Volg ons: Twitter Stedenbeleid (@vl_stedenbeleid)
- verwijzing onderaan naar goede praktijken -> verbergen

**Comment by KDaems** [comment]
Volgende bugs:
- 'meer weten over smart flanders' bovenaan stuurt naar verkeerde pagina (die van SF 2.0) -> moet naar de aparte pagina over smart flanders gaan waar uitleg staat van volledig programma met alle drie blokken in vermeld. (in die tekst staat ook een link naar datapiloten -> controleren of die juist linkt)
[Over.docx](https://github.com/smartflanders/smartflanders.github.io/files/5170041/Over.docx)

- Bij de drie blokken (SF 2.0, financiering, vloca) -> telkens onderaan 'lees meer over X' momenteel zijn alle drie anders geschreven.

- De links in blok 'financiering' en 'vloca' leiden naar nergens momenteel

- 'Direct naar': -> link datapiloten werkt niet.

- Historiek mag weggelaten worden, staat ook onder 'over' beschreven

- de links onderaan 'kennis en instrumenten' even verbergen -> leidt normaal naar overzichtspagina maar die moet ik nog maken. Is ook geen essentieel deel.

**Comment by plenaerts** [comment]
Ik zet ze efkes als todo's:

- [ ]     'meer weten over smart flanders' bovenaan stuurt naar verkeerde pagina (die van SF 2.0) -> moet naar de aparte pagina over smart flanders gaan waar uitleg staat van volledig programma met alle drie blokken in vermeld. (in die tekst staat ook een link naar datapiloten -> controleren of die juist linkt)
- [ ]     Bij de drie blokken (SF 2.0, financiering, vloca) -> telkens onderaan 'lees meer over X' momenteel zijn alle drie anders geschreven.
- [ ]     De links in blok 'financiering' en 'vloca' leiden naar nergens momenteel
- [ ]     'Direct naar': -> link datapiloten werkt niet
- [ ]     Historiek mag weggelaten worden, staat ook onder 'over' beschreven
- [ ]     de links onderaan 'kennis en instrumenten' even verbergen -> leidt normaal naar overzichtspagina maar die moet ik nog maken. Is ook geen essentieel deel.
