### ISSUE TITLE
Kennis en instrumenten in navigatie niet laten leiden naar aparte pagina

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#23]
In navigatie mag aanklikken van 'kennis en instrumenten' enkel drop down keuze geven. Overzichtspagina is voor later.

**Comment by plenaerts** [comment]
Van deze weet ik niet hoe we die moeten oplossen. Ik heb nu gezorgd dat duwen op die link je huidige positie op de site herlaadt. Een andere optie is van een pagina te voorzien met de subpagina's erin.

@KDaems OK zoals het nu in dev staat?

**Comment by KDaems** [comment]
Ok zoals het nu staat. Link naar nieuwe pagina is voor later.
