### ISSUE TITLE
Aanpassing Smart Flanders 2.0

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#28]
Overzichtspagina moet aangevuld worden met passages jaarthema en CityFlows + titels sturing en interactie toevoegen. zie doc
[Web_SF_overzichtSF2.docx](https://github.com/smartflanders/smartflanders.github.io/files/5872372/Web_SF_overzichtSF2.docx)

**Comment by FJanssen74** [comment]
done
