### ISSUE TITLE
dropdown menu Open Data Charter

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#33]
Dropdown menu voorzien zoals bij 'Kennis & Instrumenten' voor open data charter en actualisatie instrumentarium open data

**Comment by FJanssen74** [comment]
dropdown toegevoegd
Het menu item "Open Data Charter" zelf wijst nog naar de pagina die hier al stond
dit is anders dan bij Kennis & Instrumenten waar en klik op het menu item zelf eigenlijk niets doet
