### ISSUE TITLE
Links overzichtspagina Smart Flanders 2.0 toevoegen

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#35]
Volgende links invoegen in placeholders:

- citizen science: https://smart.flanders.be/smart-flanders-2.0/citizen-science 
- Cityflows: https://smart.flanders.be/smart-flanders-2.0/cityflows

**Comment by FJanssen74** [comment]
al even geleden toegevoegd

**Comment by KDaems** [comment]
Werken nog steeds niet
