### ISSUE TITLE
Niet werkende link Smart Flanders 2.0 op homepage

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#36]
Link naar Smart Flanders 2.0 op homepage werkt niet.

Moet dus leiden naar: https://smart.flanders.be/smart-flanders-2.0

**Comment by FJanssen74** [comment]
zowel in Test, Master als de huidige PRD site leidt deze link wel degelijk naar de gevraagde URL
![image](https://user-images.githubusercontent.com/60774448/114686914-82d70080-9d13-11eb-8a7c-dff6de4469cf.png)
waar exact staat de link fout?

**Comment by KDaems** [comment]
![Knipsel](https://user-images.githubusercontent.com/66940179/114723484-fc361980-9d3a-11eb-8bd4-0901374dd41f.JPG)

**Comment by KDaems** [comment]
![Knipsel](https://user-images.githubusercontent.com/66940179/114724393-c9d8ec00-9d3b-11eb-9648-baf2a732d0ff.JPG)

**Comment by FJanssen74** [comment]
done
