### ISSUE TITLE
artikel platsen

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#37]
Artikel, titel: Citizen Science voor lokale besturen - draaiboek

Gelieve artikel in bijlage te plaatsen + pdf (draaiboek)
[Citizen science voor lokale besturen.docx](https://github.com/smartflanders/smartflanders.github.io/files/6363337/Citizen.science.voor.lokale.besturen.docx)
[Draaiboek citizen science voor lokale besturen_2021.pdf](https://github.com/smartflanders/smartflanders.github.io/files/6363338/Draaiboek.citizen.science.voor.lokale.besturen_2021.pdf)

 bij artikel bij te voegen.

**Comment by FJanssen74** [comment]
done
