### ISSUE TITLE
Navigatie

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#44]
To do:
- dropdown menu bij 'hoveren' over titel navigatie ipv klikken op icoontje
- 'Open Data Charter' wijzigen naar 'Open Data Beleid'
- 'Kennis en instrumenten' wijzigen naar 'Kennisdeling'
- in footer verwijzen naar 'Open Data Beleid' ipv 'Open Data Charter'

**Comment by FJanssen74** [comment]
done in test
