### ISSUE TITLE
VLOCA

### ISSUE THREAD

**Issue by KDaems** [smartflanders/smartflanders.github.io#50]
To Do:
- Copy aanpassen (zie tekst in bijlage -> veel kleine wijzigingen dus best in geheel vervangen)
- knop 'meer weten over VLOCA' bovenaan onder de inleiding zetten.
- nieuwe knop 'meer weten over de kennsihub' onderaan zetten waar vorige knop 'meer weten over vloca' stond.
[VLOCA.docx](https://github.com/smartflanders/smartflanders.github.io/files/7078577/VLOCA.docx)

**Comment by FJanssen74** [comment]
done
